export const LOGIN_START      = 'LOGIN_START';
export const LOGIN_SUCCESS    = 'LOGIN_SUCCESS';
export const LOGIN_FAIL       = 'LOGIN_FAIL';

export const LOGOUT_START    = 'LOGOUT_START';
export const LOGOUT_SUCCESS  = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL     = 'LOGOUT_FAIL';

export const GET_AUTHENTICATED_ACCOUNT_START     = 'GET_AUTHENTICATED_ACCOUNT_START';
export const GET_AUTHENTICATED_ACCOUNT_SUCCESS   = 'GET_AUTHENTICATED_ACCOUNT_SUCCESS';
export const GET_AUTHENTICATED_ACCOUNT_FAIL      = 'GET_AUTHENTICATED_ACCOUNT_FAIL';
